<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWCyHig\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWCyHig/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWWCyHig.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWWCyHig\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWWCyHig\App_KernelDevDebugContainer([
    'container.build_hash' => 'WWCyHig',
    'container.build_id' => '8bee9f16',
    'container.build_time' => 1637740535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWCyHig');
