<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYkcxFzP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYkcxFzP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYkcxFzP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYkcxFzP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYkcxFzP\App_KernelDevDebugContainer([
    'container.build_hash' => 'YkcxFzP',
    'container.build_id' => '9f212b74',
    'container.build_time' => 1637233575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYkcxFzP');
