<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD1FkxCf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD1FkxCf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD1FkxCf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD1FkxCf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD1FkxCf\App_KernelDevDebugContainer([
    'container.build_hash' => 'D1FkxCf',
    'container.build_id' => 'cc347a8f',
    'container.build_time' => 1637747914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD1FkxCf');
